### ISSUE TITLE
Trying to open the bait GUI in 1.17rc5:

### ISSUE THREAD

**Issue by ghost** [DArkHekRoMaNT/PackingAnimals#2]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: backpackpackplus@1.0.3, betterbloomeries@1.0.1, bettercrates@1.4.2, buildingplus@1.1.2, buzzwords@1.1.0, chiseltools@1.5.4-pre.1, FindResin-texturepack@1.1.0, foundrymod@1.0.0, gravelsandfix@1.0.2, guicompositesettingsex@1.0.1, HangingOilLamps@1.0.1, midnight-texturepackNS@1.1.0, leadroof@1.1.1, nightwatcher@1.2.0, nooffhandhunger@1.0.0, notradermoneylimit@1.0.0, pieontheshelf@1.0.0, peifme@1.0.0, potontheshelf@1.0.0, preservationmod@1.0.0, primitivesurvival@3.0.5, ReducedDrifterGroupsandLightLevelSpawn@1.0.0, sod@1.0.0, SustainableForestry@1.0.0, translocatorengineeringredux@1.2.0, viescraftmachines@1.17.2, visibleore@1.0.1, vtpp@1.0.0, game@1.17.0-rc.5, WoodenPathFix@1.0.0, zoombuttonreborn@1.3.0, alchemy@1.6.4, betterdoors@1.0.0, captureanimals@2.1.1, carrycapacity@0.6.5, deathwaypoints@1.0.3, farmlanddropssoil@1.4.0, fromgoldencombs@1.3.14-pre.1, medievalexpansion@3.7.1, petool@1.0.1, prospectorinfo@3.2.0, resinlightsbymad@1.0.1, singlepause@1.0.3, stepup@1.2.0, toggly@3.0, translocatorlocator@1.0.2, useplanksinpitkiln@1.0.0, creative@1.17.0-rc.5, survival@1.17.0-rc.5, worldconfiggui@1.0.0, accessibilitytweaks@2.3.1, campaigncartographer@2.2.2, bricklayers@1.0.0-pre.3, carryablelogwithresin@1.0.0, ferrospear@1.0.1, moremolds@1.2.0
18/08/2022 20:54:34: Critical error occurred
System.MissingMethodException: Método não encontrado: 'Vintagestory.API.Client.GuiComposer Vintagestory.API.Client.GuiComposerHelpers.AddShadedDialogBG(Vintagestory.API.Client.GuiComposer, Vintagestory.API.Client.ElementBounds, Boolean, Double)'.
   em CaptureAnimals.GuiDialogBait.InitDialog()
   em CaptureAnimals.GuiDialogBait..ctor(InventoryCage inventory, ICoreClientAPI capi)
   em CaptureAnimals.InventoryCage.OnInvOpened(IPlayer player)
   em Vintagestory.API.Common.InventoryBase.Open(IPlayer player) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:linha 808
   em CaptureAnimals.ItemCage.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 860
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 835
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 563
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 89
   em Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:linha 199
   em Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:linha 1176
   em Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:linha 1364
   em Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:linha 204
   em Vintagestory.Client.ScreenManager.Render(Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:linha 706
   em Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:linha 610
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:linha 132
   em System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   em OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) na C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:linha 479
   em OpenTK.GameWindow.DispatchRenderFrame() na C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:linha 454
   em OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) na C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:linha 375
   em Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   em Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) na C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:linha 87

**Comment by DArkHekRoMaNT** [comment]
Fixed in 2.2.0
